#!/bin/sh

echo "==> Ensuring Ruby is installed (for capistrano)\n"
rbenv install -s

echo "==> Creating .env files if they aren't present\n"
[ ! -f api/.env ] && cp api/.env{.example,}
[ ! -f client/.env.local ] && cp client/.env.local{.example,}

echo "==> Rebuilding docker containers\n"
docker compose build

echo "==> We're done here! Run script/up to start the project. The frontend will be at http://localhost:3000, the backend at http://localhost:8000/admin. See README.md for more info."
