version: "3.9"
services:
  october:
    build:
      args:
        user: october
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./config/dev/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./config/dev/php-fpm.conf:/usr/local/etc/php-fpm.conf

  node:
    platform: linux/x86_64
    image: node:12.18.3-alpine
    restart: unless-stopped
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - PATH=/home/node/app/node_modules/.bin:$PATH
    volumes:
      - ./:/home/node/app
      - ./docker/bin:/home/node/bin
    ports:
      - "9090:9090"
    command: "/home/node/bin/yarn_install_and_start"

  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "8001:3306"
    environment:
      MYSQL_DATABASE: ${OCTOBER_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${OCTOBER_DB_PASSWORD}
      MYSQL_PASSWORD: ${OCTOBER_DB_PASSWORD}
      MYSQL_USER: ${OCTOBER_DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    volumes:
      - ./docker/mysql/mysqld.conf:/etc/mysql/conf.d/mysqld.conf
      - ./docker/mysql/queries:/var/lib/queries
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d

volumes:
  mysql-data:
    driver: local
